### ISSUE TITLE
Possible to add an extra js/css file

### ISSUE THREAD

**Issue by janw-oostendorp** [autonome/standalone#12]
Might not be a real question for this plugin as it's build on the webapp stuff default in FF.
But is it possible to add a extra js&css file?

**Comment by autonome** [comment]
Unfortunately, all the code that allows this add-on to work is being
removed from Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1238079

So it will likely stop working altogether at some point in the next few
releases.

**Comment by janw-oostendorp** [comment]
Mhh. Too bad.  
I understand this is a niche feature.  
I guess it fits the *Great or Dead* Philosophy.
