### ISSUE TITLE
Deprecated ?

### ISSUE THREAD

**Issue by AntoineTurmel** [autonome/standalone#13]
I assume this won't work in future version of Firefox since apps installation will be deprecated ?

**Comment by autonome** [comment]
yep. I'll add a note to the repo and the AMO page.

**Comment by AntoineTurmel** [comment]
Is there anything that will replace app installation in Firefox by any chance ?
This was a cool feature :disappointed:

**Comment by autonome** [comment]
No, there's no planned official alternative except Progressive Web Apps.
But there's no install-to-desktop plan for that on desktop browsers as far
as I know.

I'd love to be able to use the application.ini functionality in the
installed Firefox to replicate the lost functionality.

For example, here's some super old add-on code I wrote in the pre-Jetpack
days:

function loadXULRunnerApp(aIniFile) {
  var binFile = null;
  var args = [];

  var os = Cc["@mozilla.org/xre/app-info;1"].getService(Ci.nsIXULRuntime).OS;

  if (os == "Linux") {
    binFile = Cc["@mozilla.org/file/local;1"].
              createInstance(Ci.nsILocalFile);
    binFile.initWithPath("/bin/sh");
    args.push("xulrunner");
  }
  else {
    var ds = Cc["@mozilla.org/file/directory_service;1
"].getService(Ci.nsIProperties);
    var binDir = ds.get("XCurProcD", Ci.nsIFile);
    var binFile = binDir.clone();
    if (os == "WINNT")
      binFile.append("firefox.exe");
    else
      binFile.append("firefox-bin");
    if (!binFile.exists())
      Components.utils.reportError("Unable to find the executable!");
  }

  args.push("-app");
  args.push(aIniFile.path);

  var process = Cc["@mozilla.org/process/util;1"].
                createInstance(Ci.nsIProcess);
  process.init(binFile);
  process.run(false, args, args.length);
}
